a=read.csv("data_buqi1.csv",header=TRUE);head(a)
b1<-a[,-1]
b1<-b1[,-1]
b1
b1=subset(a,i==1);b1
b2=subset(a,i==2);b2
b3=subset(a,i==3);b3
install.packages("adabag")
install.packages("repart")
library("rpart")
detach("package:ipred")
library("adabag")
Ct1<-rpart.control(minsplit=20,maxcompete=4,maxdepth=30,cp=0.01,xval=10)

b1$willing=as.factor(b1$willing)#将输入变量设置为

BAg<-bagging(willing~.,data=a1,control=Ct1,mfinal=25)
weight_bagging=BAg$importance
write.csv(weight_bagging,"pinpai3_bagging.csv")
pre<-predict.bagging(BAg,b1)
as.data.frame(pre$confusion)
as.data.frame(pre$error)
class=as.data.frame(pre$class)
prob=as.data.frame(pre$prob)
a$willing_pre=class
a$prob=prob[2]

need_test=read.csv("need_test.csv",header=TRUE)
n_t<-need_test[,-59];n_t
n_t<-n_t[,-1:-2];n_t
pre1<-predict.bagging(BAg,n_t)
write.csv(class,"class_bag.csv")
pre
#bagging预测15个
BAg<-bagging(willing~.,data=a1,control=Ct1,mfinal=25)
a.pred<-predict.bagging(BAg,n1)
boos_test=a.pred$prob
boos_test0=data.frame(boos_test);boos_test0
boos_test0$class=a.pred$class;head(boos_test0)
n$pro0=boos_test0[,1]
n$pro1=boos_test0[,2]
n$class=boos_test0[,3]
write.csv(n,"bagging_test0.csv")

#推进技术
#con<-table(b1$willing,Boot$class);E4<-(sum(con)-sum(diag(con)))/sum(con);E4
#数据预处理
n=read.csv("need_test1.csv",header=TRUE);head(n)
n1<-n[,-1:-2]#去掉前两列
a=read.csv("data_buqi1.csv",header=TRUE);head(a)
test=as.data.frame(a);head(test)
a1<-a[,-1:-2]
a1$willing=as.factor(a1$willing)#将输入变量设置为
b1=subset(a,i==1);head(b1)
p1<-b1[,-1:-2]
p1$willing=as.factor(p1$willing)#将输入变量设置为
head(p1)
b2=subset(a,i==2);head(b2)
p2<-b2[,-1:-2]
p2$willing=as.factor(p2$willing)#将输入变量设置为
b3=subset(a,i==3);head(b3)
p3<-b3[,-1:-2]
p3$willing=as.factor(p3$willing)#将输入变量设置为
library("adabag")
#总数据
Boot<-boosting(willing~.,data=a1,control=Ct1,boos=TRUE,mfinal=25,coeflearn="Breiman")
write.csv(Boot$importance,"boos_impor0.csv")
a.pred=predict.boosting(Boot,newdata = a1)
a.pred$class
boos_test=a.pred$prob
boos_test0=data.frame(boos_test);boos_test0
boos_test0$class=a.pred$class;head(boos_test0)
test$pro0=boos_test0[,1]
test$pro1=boos_test0[,2]
test$class=boos_test0[,3]
write.csv(test,"boos_data0.csv")
#拿总数据预测来测试待测试
k1=n1[2,];k1
a.pred=predict.boosting(Boot,newdata = k1)
#boos_test=
a.pred$prob
boos_test0=data.frame(boos_test);boos_test0
boos_test0$class=a.pred$class;head(boos_test0)
n$pro0=boos_test0[,1]
n$pro1=boos_test0[,2]
n$class=boos_test0[,3]
write.csv(n,"boos_test0.csv")
#品牌1的数据
Boot<-boosting(willing~.,data=p1,control=Ct1,boos=TRUE,mfinal=25,coeflearn="Breiman")
write.csv(Boot$importance,"boos_impor1.csv")
a.pred=predict.boosting(Boot,newdata = p1)
a.pred$importance
boos_test=a.pred$prob
boos_test0=data.frame(boos_test);boos_test0
boos_test0$class=a.pred$class;head(boos_test0)
b1$pro0=boos_test0[,1]
b1$pro1=boos_test0[,2]
b1$class=boos_test0[,3]
write.csv(b1,"boos_data1.csv")
#品牌2的数据
Boot<-boosting(willing~.,data=p2,control=Ct1,boos=TRUE,mfinal=25,coeflearn="Breiman")
write.csv(Boot$importance,"boos_impor2.csv")
a.pred=predict.boosting(Boot,newdata = p2)
a.pred$error
boos_test=a.pred$prob
boos_test0=data.frame(boos_test);boos_test0
boos_test0$class=a.pred$class;head(boos_test0)
b2$pro0=boos_test0[,1]
b2$pro1=boos_test0[,2]
b2$class=boos_test0[,3]
write.csv(b2,"boos_data2.csv")
#品牌3的数据
Boot<-boosting(willing~.,data=p3,control=Ct1,boos=TRUE,mfinal=25,coeflearn="Breiman")
write.csv(Boot$importance,"boos_impor3.csv")
a.pred=predict.boosting(Boot,newdata = p3)
a.pred$error
boos_test=a.pred$prob
boos_test0=data.frame(boos_test);boos_test0
boos_test0$class=a.pred$class;head(boos_test0)
b3$pro0=boos_test0[,1]
b3$pro1=boos_test0[,2]
b3$class=boos_test0[,3]
write.csv(b3,"boos_data3.csv")
